CREATE TABLE IF NOT EXISTS projects (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_key VARCHAR(255) NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id BIGINT NOT NULL,
	run_key VARCHAR(255) NOT NULL UNIQUE,
	status VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	CONSTRAINT fk_analysis_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE IF NOT EXISTS java_classes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	analysis_run_id BIGINT NOT NULL,
	package_name VARCHAR(255) NOT NULL,
	class_name VARCHAR(255) NOT NULL,
	full_name VARCHAR(255) NOT NULL UNIQUE,
	annotation_type VARCHAR(255) NOT NULL,
	CONSTRAINT fk_java_class_run FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(id)
);

CREATE TABLE IF NOT EXISTS dependencies (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	analysis_run_id BIGINT NOT NULL,
	source_class VARCHAR(255) NOT NULL,
	target_class VARCHAR(255) NOT NULL,
	cycle BOOLEAN NOT NULL,
	CONSTRAINT fk_dependency_run FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(id)
);

CREATE TABLE IF NOT EXISTS metrics (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	analysis_run_id BIGINT NOT NULL,
	class_name VARCHAR(255) NOT NULL,
	lines_of_code INT NOT NULL,
	method_count INT NOT NULL,
	dependency_count INT NOT NULL,
	risk_level VARCHAR(255) NOT NULL,
	CONSTRAINT fk_metric_run FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(id)
);

CREATE TABLE IF NOT EXISTS violations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	analysis_run_id BIGINT NOT NULL,
	code VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	severity VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	description VARCHAR(2000),
	recommendation VARCHAR(2000),
	affected_classes_csv VARCHAR(2000),
	CONSTRAINT fk_violation_run FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(id)
);

CREATE TABLE IF NOT EXISTS insights (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	analysis_run_id BIGINT NOT NULL,
	code VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	description VARCHAR(2000),
	impact_level VARCHAR(255) NOT NULL,
	category VARCHAR(255) NOT NULL,
	reasoning VARCHAR(2000),
	affected_classes_csv VARCHAR(2000),
	recommendation_steps_csv VARCHAR(2000),
	CONSTRAINT fk_insight_run FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(id)
);
